// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var $, CoffeeScad, marionette, _;
    $ = require('jquery');
    _ = require('underscore');
    marionette = require('marionette');
    return CoffeeScad = (function(_super) {

      __extends(CoffeeScad, _super);

      function CoffeeScad() {
        return CoffeeScad.__super__.constructor.apply(this, arguments);
      }

      return CoffeeScad;

    })(Backbone.Marionette.Application);
  });

}).call(this);
