// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var $, Backbone, LocalStorage, Settings, _;
    $ = require('jquery');
    _ = require('underscore');
    Backbone = require('backbone');
    LocalStorage = require('localstorage');
    Settings = (function(_super) {

      __extends(Settings, _super);

      function Settings() {
        return Settings.__super__.constructor.apply(this, arguments);
      }

      Settings.prototype.localStorage = new Backbone.LocalStorage("Settings");

      Settings.prototype.defaults = {
        projects: {
          maxRecentDisplay: 5
        },
        github: {
          configured: false
        },
        codeEditor: {
          startLine: 1,
          theme: "default"
        },
        viewer: {
          antialiasing: true,
          showgrid: true
        },
        keyBindings: {
          "CTRL+Z": "undo",
          "CTRL+Y": "redo"
        }
      };

      return Settings;

    })(Backbone.Model);
    return Settings;
  });

}).call(this);
