// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var $, Backbone, LocalStorage, SettingsTest, _;
    $ = require('jquery');
    _ = require('underscore');
    Backbone = require('backbone');
    LocalStorage = require('localstorage');
    SettingsTest = (function(_super) {

      __extends(SettingsTest, _super);

      SettingsTest.prototype.id = 1;

      SettingsTest.prototype.defaults = {
        maxRecentDisplay: 5,
        tutu: 'crinoline'
      };

      SettingsTest.prototype.localStorage = new Backbone.LocalStorage("TestSettings");

      function SettingsTest(options) {
        SettingsTest.__super__.constructor.call(this, options);
      }

      return SettingsTest;

    })(Backbone.Model);
    return SettingsTest;
  });

}).call(this);
