// Generated by CoffeeScript 1.3.3

/*
#first approach
define ["jquery", "underscore", "marionette", "MyApp"], ($, _, Marionette, MyApp) ->
  
  MyModule = MyApp.module("MyModule")
  MyModule.addInitializer ->
    console.log "oi"
  
  MyApp = require('MyApp')
  
  
  
  MyApp.addInitializer (options)->
    console.log "yaargh"
*/


/*
#second approach
define (require)->
  $ = require 'jquery'
  _ = require 'underscore'
  app = require('app')
  
  app.addInitializer (options)->
    console.log "yaargh"
  
  app.vent.on "fileSaveRequest", ->
    console.log "pouer"
*/


(function() {

  define(function(require) {
    var $, MyModule, app, _;
    $ = require('jquery');
    _ = require('underscore');
    app = require('app');
    app.addInitializer(function(options) {
      return console.log("yaargh");
    });
    MyModule = app.module("MyModule");
    return MyModule.addInitializer(function() {
      return console.log("in MyModule init");
    });
  });

}).call(this);
