// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(function(require) {
    var $, Project, ProjectFile, backbone, _;
    $ = require('jquery');
    _ = require('underscore');
    backbone = require('backbone');
    ProjectFile = (function(_super) {

      __extends(ProjectFile, _super);

      ProjectFile.prototype.defaults = {
        name: "main",
        ext: "coscad",
        content: ""
      };

      function ProjectFile(options) {
        ProjectFile.__super__.constructor.call(this, options);
      }

      return ProjectFile;

    })(backbone.Model);
    Project = (function(_super) {

      __extends(Project, _super);

      function Project() {
        this.initialize = __bind(this.initialize, this);
        return Project.__super__.constructor.apply(this, arguments);
      }

      Project.prototype.model = ProjectFile;

      Project.prototype.initialize = function(options) {};

      Project.prototype["export"] = function(format) {};

      return Project;

    })(Backbone.Collection);
    return [ProjectFile, Project];
  });

  /*
    initialize:(options)->
      @bind "change:name", ()=>
        name = @get "name"
        console.log "Changed my name to " + name
  */


}).call(this);
