// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var getBlobBuilder, getWindowURL, revokeBlobUrl, textToBlobUrl;
    getBlobBuilder = function() {
      bb;

      var bb;
      if (window.BlobBuilder) {
        bb = new window.BlobBuilder();
      } else if (window.WebKitBlobBuilder) {
        bb = new window.WebKitBlobBuilder();
      } else if (window.MozBlobBuilder) {
        bb = new window.MozBlobBuilder();
      } else {
        throw new Error("Your browser doesn't support BlobBuilder");
      }
      return bb;
    };
    getWindowURL = function() {
      if (window.URL) {
        return window.URL;
      } else if (window.webkitURL) {
        return window.webkitURL;
      } else {
        throw new Error("Your browser doesn't support window.URL");
      }
    };
    textToBlobUrl = function(txt) {
      var bb, blob, blobURL, windowURL;
      bb = getBlobBuilder();
      windowURL = getWindowURL();
      bb.append(txt);
      blob = bb.getBlob();
      blobURL = windowURL.createObjectURL(blob);
      if (!blobURL) {
        throw new Error("createObjectURL() failed");
      }
      return blobURL;
    };
    revokeBlobUrl = function(url) {
      if (window.URL) {
        return window.URL.revokeObjectURL(url);
      } else if (window.webkitURL) {
        return window.webkitURL.revokeObjectURL(url);
      } else {
        throw new Error("Your browser doesn't support window.URL");
      }
    };
    return {
      "getBlobBuilder": getBlobBuilder,
      "getWindowURL": getWindowURL,
      "textToBlobUrl": textToBlobUrl,
      "revokeBlobUrl": revokeBlobUrl
    };
  });

}).call(this);
