// Generated by CoffeeScript 1.3.3
(function() {
  var Project;

  Project = (function() {

    function Project(name, content) {
      this.name = name;
      this.content = content;
    }

    Project.prototype["export"] = function(format) {};

    Project.prototype.save = function() {};

    Project.prototype.load = function() {};

    return Project;

  })();

}).call(this);
