// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var Editor, Router, app, coscad;
    app = require('app');
    Router = require('router');
    Editor = require('editor');
    coscad = require('opencoffeescad');
    app.router = new Router();
    app.cadViewer = new coscad.Viewer(document.getElementById("viewer"), 750, 750);
    app.cadProcessor = new coscad.Processor(true, null, document.getElementById("statusBar"), app.cadViewer);
    app.cadEditor = new Editor();
    app.updateSolid();
    Backbone.history.start({
      pushState: true,
      root: app.root
    });
    return $(document).on("click", "a[href]:not([data-bypass])", function(evt) {
      var href, root;
      href = {
        prop: $(this).prop("href"),
        attr: $(this).attr("href")
      };
      root = location.protocol + "//" + location.host + app.root;
      if (href.prop.slice(0, root.length) === root) {
        evt.preventDefault();
        Backbone.history.navigate(href.attr, true);
      }
    });
  });

}).call(this);
