// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var OpenCoffeeScad, Processor, Store, Viewer;
    Viewer = require('viewer');
    Processor = require('processor');
    Store = require('DataStore');
    OpenCoffeeScad = {};
    OpenCoffeeScad.Viewer = Viewer;
    OpenCoffeeScad.Processor = Processor;
    OpenCoffeeScad.Store = Store;
    window.OpenCoffeeScad = OpenCoffeeScad;
    OpenCoffeeScad.log = function(txt) {
      var deltatime, prevtime, timeInMs;
      timeInMs = Date.now();
      prevtime = OpenCoffeeScad.log.prevLogTime;
      prevtime = !prevtime ? timeInMs : void 0;
      deltatime = timeInMs - prevtime;
      return OpenCoffeeScad.log.prevLogTime = timeInMs;
      /*timefmt = (deltatime*0.001).toFixed(3)
      txt = "["+timefmt+"] "+txt
      if (typeof(console) == "object") && (typeof(console.log) == "function") 
        console.log(txt)
      else if (typeof(self) == "object") && (typeof(self.postMessage) == "function") 
        self.postMessage({cmd: 'log', txt: txt})
      else throw new Error("Cannot log")
      */

    };
    OpenCoffeeScad.isChrome = function() {
      return navigator.userAgent.search("Chrome") >= 0;
    };
    return OpenCoffeeScad;
  });

}).call(this);
