// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  OpenCoffeeScad.ProjectFile = (function(_super) {

    __extends(ProjectFile, _super);

    function ProjectFile() {
      this.initialize = __bind(this.initialize, this);
      return ProjectFile.__super__.constructor.apply(this, arguments);
    }

    ProjectFile.prototype.defaults = {
      name: "MyProject",
      content: ""
    };

    ProjectFile.prototype.initialize = function(options) {};

    return ProjectFile;

  })(Backbone.Model);

  OpenCoffeeScad.Project = (function(_super) {

    __extends(Project, _super);

    function Project() {
      this.initialize = __bind(this.initialize, this);
      return Project.__super__.constructor.apply(this, arguments);
    }

    Project.prototype.model = OpenCoffeeScad.ProjectFile;

    Project.prototype.initialize = function(options) {
      return this.all_files_saved = false;
    };

    Project.prototype["export"] = function(format) {};

    return Project;

  })(Backbone.Collection);

}).call(this);
