// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var $, DialogRegion, boostrap, jquery_ui, marionette, _;
    $ = require('jquery');
    _ = require('underscore');
    boostrap = require('bootstrap');
    marionette = require('marionette');
    jquery_ui = require('jquery_ui');
    DialogRegion = (function(_super) {

      __extends(DialogRegion, _super);

      DialogRegion.prototype.el = "#dialogRegion";

      function DialogRegion() {
        this.showModal = __bind(this.showModal, this);
        _.bindAll(this);
        this.on("view:show", this.showModal, this);
      }

      DialogRegion.prototype.getEl = function(selector) {
        var $el;
        $el = $(selector);
        $el.on("hidden", this.close);
        return $el;
      };

      DialogRegion.prototype.showModal = function(view) {
        view.on("close", this.hideModal, this);
        return $("#dialog").dialog({
          title: "Part Code Editor",
          width: 550,
          height: 700,
          position: {
            my: "right center",
            at: "right bottom"
          }
        });
        /*
              $(".draggable").draggable
                grid: [ 1, 1 ]
              $(".draggable").resizable
                handles : "se"
        */

      };

      DialogRegion.prototype.hideModal = function() {
        return this.$el.modal('hide');
      };

      return DialogRegion;

    })(Backbone.Marionette.Region);
    return DialogRegion;
  });

}).call(this);
