// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var $, LoadView, SaveView, boostrap, lF_template, marionette, sF_template, _;
    $ = require('jquery');
    _ = require('underscore');
    boostrap = require('bootstrap');
    marionette = require('marionette');
    sF_template = require("text!templates/saveFile.tmpl");
    lF_template = require("text!templates/loadFile.tmpl");
    SaveView = (function(_super) {

      __extends(SaveView, _super);

      SaveView.prototype.template = sF_template;

      SaveView.prototype.ui = {
        fileNameInput: "#projectFileName"
      };

      SaveView.prototype.triggers = {
        "mouseup .saveFile": "file:save:mouseup"
      };

      function SaveView(options) {
        var _this = this;
        SaveView.__super__.constructor.call(this, options);
        this.app = require('app');
        this.on("file:save:mouseup", function() {
          var fileName;
          fileName = $(_this.ui.fileNameInput).val();
          _this.app.vent.trigger("fileSaveRequest", fileName);
          return _this.close();
        });
      }

      return SaveView;

    })(marionette.ItemView);
    LoadView = (function(_super) {

      __extends(LoadView, _super);

      LoadView.prototype.template = lF_template;

      LoadView.prototype.ui = {
        fileNameInput: "#projectFileName"
      };

      LoadView.prototype.triggers = {
        "mouseup .loadFile": "file:load:mouseup"
      };

      function LoadView(options) {
        var _this = this;
        LoadView.__super__.constructor.call(this, options);
        this.app = require('app');
        this.on("file:load:mouseup", function() {
          var fileName;
          fileName = $(_this.ui.fileNameInput).val();
          _this.app.vent.trigger("fileLoadRequest", fileName);
          return _this.close();
        });
      }

      return LoadView;

    })(marionette.ItemView);
    return {
      SaveView: SaveView,
      LoadView: LoadView
    };
  });

}).call(this);
