// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var $, FileBrowseRegion, FileBrowserView, SingleFileView, boostrap, dummyTemplate, fileBrowserSingleTemplate, fileBrowserTemplate, jquery_ui, jstree, marionette, _;
    $ = require('jquery');
    _ = require('underscore');
    boostrap = require('bootstrap');
    marionette = require('marionette');
    jstree = require('jquery_jstree');
    dummyTemplate = require("text!templates/dummy.tmpl");
    fileBrowserSingleTemplate = require("text!templates/fileBrowserSingle.tmpl");
    fileBrowserTemplate = require("text!templates/fileBrowser.tmpl");
    jquery_ui = require('jquery_ui');
    FileBrowseRegion = (function(_super) {

      __extends(FileBrowseRegion, _super);

      FileBrowseRegion.prototype.el = "#none";

      function FileBrowseRegion(options) {
        this.showModal = __bind(this.showModal, this);
        FileBrowseRegion.__super__.constructor.call(this, options);
        this.makeEl();
        this.$el = $("#fileBrowseRegion");
        _.bindAll(this);
        this.on("view:show", this.showModal, this);
      }

      FileBrowseRegion.prototype.makeEl = function() {
        return $('<div/>', {
          id: 'fileBrowseRegion'
        }).appendTo('body');
      };

      FileBrowseRegion.prototype.getEl = function(selector) {
        var $el;
        $el = $(selector);
        $el.on("hidden", this.close);
        return $el;
      };

      FileBrowseRegion.prototype.showModal = function(view) {
        var $el,
          _this = this;
        $el = this.getEl();
        view.isVisible = true;
        return this.$el.dialog({
          title: "Projects",
          width: 200,
          height: 400,
          position: {
            my: "left center",
            at: "left center"
          },
          beforeClose: function() {
            view.isVisible = false;
            return view.close();
          }
        });
      };

      FileBrowseRegion.prototype.hideModal = function() {
        return this.$el.modal('hide');
      };

      return FileBrowseRegion;

    })(Backbone.Marionette.Region);
    SingleFileView = (function(_super) {

      __extends(SingleFileView, _super);

      SingleFileView.prototype.template = fileBrowserSingleTemplate;

      SingleFileView.prototype.tagName = "ul";

      SingleFileView.prototype.templateHelpers = {
        renderFiles: function() {
          var fileInfo, item, pfile, _i, _len, _ref;
          fileInfo = "";
          fileInfo += "<li class='loadFileDirect'><a href='#' class='loadFileDirect'>mainpart.coscad</a></li>";
          _ref = this.pfiles;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            pfile = _ref[_i];
            item = "<li class='loadFileDirect'><a href='#'>" + (pfile.get('name')) + "</a></li>";
            fileInfo += item;
          }
          return fileInfo;
        }
      };

      function SingleFileView(options) {
        this.requestFileLoad = __bind(this.requestFileLoad, this);
        SingleFileView.__super__.constructor.call(this, options);
        this.app = require('app');
      }

      SingleFileView.prototype.events = {
        "mouseup .loadFileDirect": "requestFileLoad"
      };

      SingleFileView.prototype.requestFileLoad = function(ev) {
        var fileName;
        fileName = $(ev.currentTarget).html();
        return console.log("requesting " + fileName);
      };

      return SingleFileView;

    })(Backbone.Marionette.ItemView);
    FileBrowserView = (function(_super) {

      __extends(FileBrowserView, _super);

      FileBrowserView.prototype.itemView = SingleFileView;

      function FileBrowserView(options) {
        FileBrowserView.__super__.constructor.call(this, options);
        this.app = require('app');
      }

      FileBrowserView.prototype.onRender = function(options) {
        var customMenu, tmp,
          _this = this;
        customMenu = function(node) {
          var items;
          items = {
            deleteItem: {
              label: "Delete",
              action: function() {
                console.log("aie aie");
                console.log($(node));
                if ($(node).hasClass("folder")) {
                  delete items.deleteItem;
                  return this.render();
                }
              }
            }
          };
          if ($(node).hasClass("folder")) {
            delete items.deleteItem;
          }
          return items;
        };
        tmp = this.$el.jstree({
          "core": {
            "animation": 0
          },
          "plugins": ["html_data", "ui", "contextmenu", "themeroller"],
          "contextmenu": {
            "items": customMenu
          }
          /*"themes":
            "theme": "default",
            "dots": true,
            "icons": false,
          */

          /* 
          "html_data" : 
            "data" : """
            <li id='root'>
              <a href='#'>Root node</a>
              <ul><li><a href='#'>Child node</a></li></ul>
              <ul><li><a href='#'>Child node2</a></li></ul>
              <ul>
                <li>
                  <a href='#'>Child node2</a>
                  <ul>
                    <li><a href='#'>Child node2 sub 1</a></li>
                  </ul>
                </li>
              </ul>
            </li>"""
          */

        });
        this.$el.bind("open_node.jstree close_node.jstree", function(e) {
          return console.log("tutupouet");
        });
        return this.$el.bind("select_node.jstree", function(event, data) {
          var fileName, id;
          id = $.jstree._focused().get_selected().attr("id");
          fileName = id.slice(7, id.length + 1 || 9e9);
          return _this.app.vent.trigger("fileLoadRequest", fileName);
        });
      };

      return FileBrowserView;

    })(Backbone.Marionette.CollectionView);
    return {
      FileBrowserView: FileBrowserView,
      FileBrowseRegion: FileBrowseRegion
    };
  });

}).call(this);
