// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var ThreeGlView, csg, lightgl, marionette, threedView_template;
    lightgl = require('lightgl');
    csg = require('csg');
    marionette = require('marionette');
    threedView_template = require("text!templates/3dview.tmpl");
    ThreeGlView = (function(_super) {

      __extends(ThreeGlView, _super);

      function ThreeGlView() {
        return ThreeGlView.__super__.constructor.apply(this, arguments);
      }

      ThreeGlView.prototype.template = threedView_template;

      return ThreeGlView;

    })(marionette.ItemView);
    return ThreeGlView;
  });

}).call(this);
