// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var $, MainMenuView, mainMenu_template, marionette, _;
    $ = require('jquery');
    _ = require('underscore');
    marionette = require('marionette');
    mainMenu_template = require("text!templates/mainMenu.tmpl");
    MainMenuView = (function(_super) {
      var get_recentProjects;

      __extends(MainMenuView, _super);

      function MainMenuView() {
        this.onRender = __bind(this.onRender, this);

        this.onBeforeRender = __bind(this.onBeforeRender, this);
        return MainMenuView.__super__.constructor.apply(this, arguments);
      }

      MainMenuView.prototype.template = mainMenu_template;

      MainMenuView.prototype.triggers = {
        "click .newFile": "file:new:clicked",
        "click .saveFile": "file:save:clicked",
        "click .loadFile": "file:load:clicked"
      };

      get_recentProjects = function() {
        var index, item, project, value, _ref, _results;
        _ref = store.get_files("local");
        _results = [];
        for (index in _ref) {
          project = _ref[index];
          value = project;
          item = "<li><a tabindex='-1' href='#' >" + value + "</a></li>";
          $('#recentFilesList').append(item);
          _results.push($('#fileLoadModalFileList').append(item));
        }
        return _results;
      };

      MainMenuView.prototype.onBeforeRender = function() {};

      MainMenuView.prototype.onRender = function() {};

      return MainMenuView;

    })(marionette.CompositeView);
    return MainMenuView;
  });

}).call(this);
